# (c) Copyright IBM Corp. 2016.  All Rights Reserved.
# Distributed under the terms of the Modified BSD License.

version: "2"

services:
  notebook:
    build: .
    image: zos-spark/i2w-notebook
    container_name: ${NAME}
    volumes:
     - "work:/home/jovyan/work"
    ports:
     - "${PORT}:8888"

volumes:
  work:
    external:
      name: ${WORK_VOLUME}
